---
title: "AOC2022 Day 2"
output: github_document
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(janitor)
```


# Data Load and Clean
```{r data_load}
choices <- c('rock', 'paper', 'scissors')

choice_map <- tibble(code = c('A', 'B', 'C', 'X', 'Y', 'Z'),
                     choice = c(choices, choices))

shape_scores <- tibble(myself = choices, shape_score =  c(1, 2, 3))

outcome_scores <- tibble(opponent = choices) %>%
  crossing(tibble(myself = choices)) %>%
  arrange(opponent, myself) %>%
  mutate(outcome_score = c(3,0,6,6,3,0,0,6,3))

data <- read_delim('data/day2.txt',
                   delim = ' ',
                   col_names = c('opponent', 'myself'),
                   col_types = cols(opponent = col_character(), myself = col_character())) %>%
  inner_join(choice_map %>% rename(opponent = code), by="opponent") %>%
  select(-opponent) %>% rename(opponent = choice) %>%
  inner_join(choice_map %>% rename(myself = code), by="myself") %>%
  select(-myself) %>% rename(myself = choice) %>%
  mutate(round = row_number())
data
```

# Part 1
```{r part1}
data %>%
  inner_join(shape_scores, by = "myself") %>%
  inner_join(outcome_scores, by = c("opponent", "myself")) %>%
  mutate(score = shape_score + outcome_score) %>%
  select(opponent, score) %>%
  adorn_totals() %>% as_tibble() %>%
  filter(opponent == 'Total')
```


# Part 2
```{r part2}
instructions = tibble(myself = c('rock', 'paper', 'scissors'),
                      outcome_score = c(0, 3, 6))
data %>%
  inner_join(instructions, by = "myself") %>%
  select(-myself) %>%
  inner_join(outcome_scores, by = c("opponent", "outcome_score")) %>%
  inner_join(shape_scores, by = "myself") %>%
  mutate(score = shape_score + outcome_score) %>%
  select(opponent, score) %>%
  adorn_totals() %>% as_tibble() %>%
  filter(opponent == 'Total')
```